"""backends interfaces only; no registered provider implementation."""
from typing import Protocol
from physical_harness.wire import WireObject


class DeviceBackend(Protocol):
    """Provider boundary; invocation requires a future concrete adapter."""
    async def connect(self, configuration: WireObject) -> None: ...
    async def status(self) -> WireObject: ...
    async def command(self, command: WireObject, idempotency_key: str) -> WireObject: ...
    async def pause(self) -> WireObject: ...
    async def stop(self) -> WireObject: ...
    async def disconnect(self) -> None: ...
