"""environments interfaces only; no registered provider implementation."""
from typing import Protocol
from physical_harness.wire import WireObject


class EnvironmentAdapter(Protocol):
    """Provider boundary; invocation requires a future concrete adapter."""
    async def describe(self) -> WireObject: ...
    async def reset(self, configuration: WireObject) -> WireObject: ...
    async def observe(self) -> WireObject: ...
    async def step(self, action: WireObject) -> WireObject: ...
    async def close(self) -> None: ...
