"""execution interfaces only; no registered provider implementation."""
from typing import Protocol
from physical_harness.wire import WireObject


class ExecutionWorker(Protocol):
    """Provider boundary; invocation requires a future concrete adapter."""
    async def submit(self, request: WireObject, idempotency_key: str) -> str: ...
    async def query(self, execution_id: str) -> WireObject: ...
    async def pause(self, execution_id: str) -> None: ...
    async def stop(self, execution_id: str) -> None: ...
