"""policies interfaces only; no registered provider implementation."""
from typing import Protocol
from physical_harness.wire import WireObject


class SubgoalPolicy(Protocol):
    """Provider boundary; invocation requires a future concrete adapter."""
    async def describe(self) -> WireObject: ...
    async def start(self, subgoal: WireObject) -> str: ...
    async def next_action(self, policy_session: str, observation: WireObject) -> WireObject: ...
    async def close(self, policy_session: str) -> None: ...
